### ISSUE TITLE
Не работает окно смены начальной даты

### ISSUE THREAD

**Issue by grosslarnakh** [grosslarnakh/pm#1]
![2016-08-15 19 23 29](https://cloud.githubusercontent.com/assets/508445/17671172/9183e26e-6326-11e6-8ec2-6951f7ba4cbc.jpg)

**Comment by grosslarnakh** [comment]
По нажатию на 15 Aug 16 выскакивает ошибка.

**Comment by aaleksu** [comment]
А других ошибок нет?
По идее, когда открываешь sample.html не через настроенный локально хост, а как просто html, должна сыпаться ошибка "Cross origin requests are only supported for protocol schemes".

**Comment by aaleksu** [comment]
Исправлено. Закрываю
